# Generated by scripts/gen-homebrew-cask.mjs — do not edit by hand.
# Regenerate with `make brew-cask`; CI republishes it on every release.
cask "diff-bro" do
  version "0.1.11"
  sha256 "73278d8acbd05223de1da22830af53311302d2c0592948aa8d280ee542b102ca"

  url "https://github.com/mindaugaskasp/diff-bro/releases/download/v#{version}/diff-bro-v#{version}.dmg"
  name "Diff Bro"
  desc "Offline-only desktop diff viewer"
  homepage "https://github.com/mindaugaskasp/diff-bro"

  # The DMG carries an arm64-only build, and Electron 39 sets
  # LSMinimumSystemVersion 12.0. Declared so `brew install` refuses up
  # front on an unsupported Mac instead of staging an app that cannot run.
  # A bare macOS symbol is Homebrew's ">= that version" form.
  depends_on arch: :arm64
  depends_on macos: :monterey

  app "Diff Bro.app"

  # Saved diffs, the identity keypair and window state live outside the app
  # bundle, so a plain uninstall leaves them behind. `brew uninstall --zap`
  # is the documented way to remove them too.
  zap trash: [
    "~/Library/Application Support/diffbro",
    "~/Library/Preferences/com.mindaugas.diffbro.plist",
    "~/Library/Saved Application State/com.mindaugas.diffbro.savedState",
  ]

  # ALPHA build: not signed or notarized (see DEVELOPMENT_PLAN.md Phase 3), so
  # macOS quarantines it and Gatekeeper reports it "damaged". We clear the
  # quarantine flag in postflight so `brew install` just works. This bypasses
  # Gatekeeper's check on THIS app — an accepted trade only because Homebrew has
  # already verified the download against the pinned sha256 above, and the
  # caveat below tells users plainly what they're installing. `must_succeed:
  # false` keeps a no-op strip (flag already absent) from failing the install.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Diff Bro.app"],
                   must_succeed: false
  end

  caveats <<~EOS
    ⚠️  ALPHA / development build — NOT signed or notarized by Apple.

    On install, Diff Bro's Gatekeeper quarantine flag is cleared automatically
    so the app will open. That means macOS does NOT vet this build for you —
    only install it if you trust this source. Expect rough edges and breaking
    changes between releases.
  EOS
end
