# Generated by scripts/gen-homebrew-cask.mjs — do not edit by hand.
# Regenerate with `make brew-cask`; CI republishes it on every release.
cask "diff-bro" do
  version "0.1.9"
  sha256 "c56eb0a20d52f538c75d5e47a49891bf59e7754aa883b77289dd648809d7d9a4"

  url "https://github.com/mindaugaskasp/diff-bro/releases/download/v#{version}/diff-bro-v#{version}.dmg"
  name "Diff Bro"
  desc "Offline-only desktop diff viewer"
  homepage "https://github.com/mindaugaskasp/diff-bro"

  # The DMG carries an arm64-only build, and Electron 39 sets
  # LSMinimumSystemVersion 12.0. Declared so `brew install` refuses up
  # front on an unsupported Mac instead of staging an app that cannot run.
  # A bare macOS symbol is Homebrew's ">= that version" form.
  depends_on arch: :arm64
  depends_on macos: :monterey

  app "Diff Bro.app"

  # Saved diffs, the identity keypair and window state live outside the app
  # bundle, so a plain uninstall leaves them behind. `brew uninstall --zap`
  # is the documented way to remove them too.
  zap trash: [
    "~/Library/Application Support/diffbro",
    "~/Library/Preferences/com.mindaugas.diffbro.plist",
    "~/Library/Saved Application State/com.mindaugas.diffbro.savedState",
  ]

  # The build is not yet signed/notarized (see DEVELOPMENT_PLAN.md Phase 3), so
  # Gatekeeper quarantines it. Homebrew 6 removed `--no-quarantine` (the flag
  # now errors out, and HOMEBREW_CASK_OPTS no longer honours it either), so
  # clearing the flag afterwards is the only route left.
  caveats <<~EOS
    Diff Bro is not yet signed or notarized, so macOS quarantines it on
    install and may report it as "damaged". Clear the flag once:

      xattr -dr com.apple.quarantine "#{appdir}/Diff Bro.app"

    then open it normally.
  EOS
end
